### ISSUE TITLE
SAP HTTP Port must be 4 character long

### ISSUE THREAD

**Issue by antsetia** [Azure/Azure-Monitor-for-SAP-solutions-preview#34]
Hi Team,

I am adding provider for SAP Netweaver and found that the SAP HTTP Port must be 4 character long.
When my SAP Netweaver HTTP Port is 80 then I found that I must configured it as 0080, and works, Kindly advise is this the best practice to configure for SAP port less than 4 character ?

Could you help to advise, how is the HTTP Port is more than 4 character, for example like SOLMAN Java that has port 50200 (when instance number is 02) ? How we could set this ?

Thank you
Anton

**Comment by hsridharan** [comment]
Hello @antsetia 

This is a bug on our end and we are working towards getting this fixed as soon as possible.
I can keep you posted in the same thread once the fix is deployed.

As a temporary workaround, is it possible to update the HTTP port to 4-digit numbers in SAP and try creating the Netweaver provider? 

Thanks,
Harsha

**Comment by hsridharan** [comment]
Hello @antsetia ,

Hope this is working for you now. Please confirm and we can close this issue. 

![image](https://user-images.githubusercontent.com/74435183/176023065-517d13be-8ce6-44a5-a747-1a19f6e43c7d.png)

Thanks,
Harsha
