### ISSUE TITLE
Unable to create AMS instance resource

### ISSUE THREAD

**Issue by Abhay-Anand149** [Azure/Azure-Monitor-for-SAP-solutions-preview#40]
{
    "status": "Failed",
    "error": {
        "code": "MonitorResourceCreationFailed",
        "message": "\n      The resource creation for the create monitor operation has failed.\n      Possible Causes: The operation failed due to an internal error.\n      Recommended Action: Retry the operation. If the issue persists, please create an issue here :- https://aka.ms/AAgc4fy.\n    "
    }
}

**Comment by archanak-msft** [comment]
@Naveen ***@***.***>
@Hiren ***@***.***>
@Nitin ***@***.***>
@Prajjwal ***@***.***>

@Hiren ***@***.***> - please confirm if this is related to the fixes for which deployment is in progress.

-Archana
________________________________
From: Abhay-Anand149 ***@***.***>
Sent: Tuesday, July 12, 2022 6:59:02 PM
To: Azure/Azure-Monitor-for-SAP-solutions-preview ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/Azure-Monitor-for-SAP-solutions-preview] Unable to create AMS instance resource (Issue #40)


{
"status": "Failed",
"error": {
"code": "MonitorResourceCreationFailed",
"message": "\n The resource creation for the create monitor operation has failed.\n Possible Causes: The operation failed due to an internal error.\n Recommended Action: Retry the operation. If the issue persists, please create an issue here :- https://aka.ms/AAgc4fy.\n<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAAgc4fy.%255Cn&data=05%7C01%7CKatiyar.Archana%40microsoft.com%7C0a45cd5ce64c434cbfec08da640a7d04%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637932293496500920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F3EzSqZIgN2NfiNaFDFfXi1q1a%2BOCEAAFN8RTuPswu4%3D&reserved=0> "
}
}

**Comment by hirenchalodiya1** [comment]
Hello @Abhay-Anand149 
Can I get correction ID of the request or subscription ID, resource name, workload region you're trying?

**Comment by M2skills** [comment]
Hello @Abhay-Anand149
Can we close the incident?
